openapi: 3.0.0
info:
  title: SubPackageFeatureBlocksResponse API
  version: 1.0.0
paths:
  /sub_package_feature_blocks:
    get:
      operationId: listSubPackageFeatureBlocks
      summary: Get all sub_package_feature_blocks
      responses:
        '200':
          description: List of sub_package_feature_blocks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubPackageFeatureBlocksResponse'
    post:
      operationId: createSubPackageFeatureBlock
      summary: Create a new sub_package_feature_blocks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubPackageFeatureBlocksRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubPackageFeatureBlocksResponse'

  /sub_package_feature_blocks/{id}:
    get:
      operationId: getSubPackageFeatureBlocksById
      summary: Get sub_package_feature_blocks by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: sub_package_feature_blocks object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubPackageFeatureBlocksResponse'
    put:
      operationId: updateSubPackageFeatureBlock
      summary: Update sub_package_feature_blocks by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubPackageFeatureBlocksRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubPackageFeatureBlocksResponse'
    delete:
      operationId: deleteSubPackageFeatureBlock
      summary: Delete sub_package_feature_blocks by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    SubPackageFeatureBlocksRequest:
      type: object
      properties:
        id:
          type: integer
        sub_package_feature_id:
          type: integer
        block_id:
          type: integer
        is_selected:
          type: string
        deleted_at:
          type: string
          format: date-time

    SubPackageFeatureBlocksResponse:
      type: object
      properties:
        id:
          type: integer
        sub_package_feature_id:
          type: integer
        block_id:
          type: integer
        is_selected:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
  
