openapi: 3.0.0
info:
  title: PackageRoleMappingsResponse API
  version: 1.0.0
paths:
  /package_role_mappings:
    get:
      operationId: listPackageRoleMappings
      summary: Get all package_role_mappings
      responses:
        '200':
          description: List of package_role_mappings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PackageRoleMappingsResponse'
    post:
      operationId: createPackageRoleMapping
      summary: Create a new package_role_mappings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PackageRoleMappingsRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PackageRoleMappingsResponse'

  /package_role_mappings/{id}:
    get:
      operationId: getPackageRoleMappingsById
      summary: Get package_role_mappings by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: package_role_mappings object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PackageRoleMappingsResponse'
    put:
      operationId: updatePackageRoleMapping
      summary: Update package_role_mappings by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PackageRoleMappingsRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PackageRoleMappingsResponse'
    delete:
      operationId: deletePackageRoleMapping
      summary: Delete package_role_mappings by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    PackageRoleMappingsRequest:
      type: object
      properties:
        id:
          type: integer
        package_role_id:
          type: integer
        package_id:
          type: integer

    PackageRoleMappingsResponse:
      type: object
      properties:
        id:
          type: integer
        package_role_id:
          type: integer
        package_id:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  
