openapi: 3.0.0
info:
  title: CrmsResponse API
  version: 1.0.0
paths:
  /crms:
    get:
      operationId: listCrms
      summary: Get all crms
      responses:
        '200':
          description: List of crms
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CrmsResponse'
    post:
      operationId: createCrm
      summary: Create a new crms
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CrmsRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrmsResponse'

  /crms/{id}:
    get:
      operationId: getCrmsById
      summary: Get crms by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: crms object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrmsResponse'
    put:
      operationId: updateCrm
      summary: Update crms by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CrmsRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrmsResponse'
    delete:
      operationId: deleteCrm
      summary: Delete crms by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    CrmsRequest:
      type: object
      properties:
        domain:
          type: string
          maxLength: 100
        cpanel_id:
          type: integer

    CrmsResponse:
      type: object
      properties:
        id:
          type: integer
        domain:
          type: string
          maxLength: 100
        cpanel_id:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  
