openapi: 3.0.0
info:
  title: PackageFeatureBlocksResponse API
  version: 1.0.0
paths:
  /package_feature_blocks:
    get:
      operationId: listPackageFeatureBlocks
      summary: Get all package_feature_blocks
      responses:
        '200':
          description: List of package_feature_blocks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PackageFeatureBlocksResponse'
    post:
      operationId: createPackageFeatureBlock
      summary: Create a new package_feature_blocks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PackageFeatureBlocksRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PackageFeatureBlocksResponse'

  /package_feature_blocks/{id}:
    get:
      operationId: getPackageFeatureBlocksById
      summary: Get package_feature_blocks by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: package_feature_blocks object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PackageFeatureBlocksResponse'
    put:
      operationId: updatePackageFeatureBlock
      summary: Update package_feature_blocks by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PackageFeatureBlocksRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PackageFeatureBlocksResponse'
    delete:
      operationId: deletePackageFeatureBlock
      summary: Delete package_feature_blocks by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    PackageFeatureBlocksRequest:
      type: object
      properties:
        id:
          type: integer
        package_feature_id:
          type: integer
        block_id:
          type: integer

    PackageFeatureBlocksResponse:
      type: object
      properties:
        id:
          type: integer
        package_feature_id:
          type: integer
        block_id:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  
