openapi: 3.0.0
info:
  title: PackagesResponse API
  version: 1.0.0
paths:
  /packages:
    get:
      operationId: listPackages
      summary: Get all packages
      responses:
        '200':
          description: List of packages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PackagesResponse'
    post:
      operationId: createPackage
      summary: Create a new packages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PackagesRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PackagesResponse'

  /packages/{id}:
    get:
      operationId: getPackagesById
      summary: Get packages by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: packages object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PackagesResponse'
    put:
      operationId: updatePackage
      summary: Update packages by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PackagesRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PackagesResponse'
    delete:
      operationId: deletePackage
      summary: Delete packages by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    PackagesRequest:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 200
        price:
          type: number
        cost_price:
          type: number
        industry_id:
          type: integer
        max_users:
          type: integer
        package_type:
          type: string
        status:
          type: string
        allowed_multiple_stores:
          type: string
        additional_price:
          type: number
        additional_cost_price:
          type: number
        permission_based_on:
          type: string
        test_package:
          type: string

    PackagesResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 200
        price:
          type: number
        cost_price:
          type: number
        industry_id:
          type: integer
        max_users:
          type: integer
        package_type:
          type: string
        status:
          type: string
        allowed_multiple_stores:
          type: string
        additional_price:
          type: number
        additional_cost_price:
          type: number
        permission_based_on:
          type: string
        test_package:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  
