openapi: 3.0.0
info:
  title: CustomerDocumentsResponse API
  version: 1.0.0
paths:
  /customer_documents:
    get:
      operationId: listCustomerDocuments
      summary: Get all customer_documents
      responses:
        '200':
          description: List of customer_documents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerDocumentsResponse'
    post:
      operationId: createCustomerDocument
      summary: Create a new customer_documents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDocumentsRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDocumentsResponse'

  /customer_documents/{id}:
    get:
      operationId: getCustomerDocumentsById
      summary: Get customer_documents by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: customer_documents object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDocumentsResponse'
    put:
      operationId: updateCustomerDocument
      summary: Update customer_documents by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDocumentsRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDocumentsResponse'
    delete:
      operationId: deleteCustomerDocument
      summary: Delete customer_documents by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    CustomerDocumentsRequest:
      type: object
      properties:
        id:
          type: integer
        customer_id:
          type: integer
        document_name:
          type: string
          maxLength: 300
        file_name:
          type: string
          maxLength: 300
        document_type_id:
          type: integer
        created_by:
          type: integer
        updated_by:
          type: integer
        deleted_at:
          type: string
          format: date-time

    CustomerDocumentsResponse:
      type: object
      properties:
        id:
          type: integer
        customer_id:
          type: integer
        document_name:
          type: string
          maxLength: 300
        file_name:
          type: string
          maxLength: 300
        document_type_id:
          type: integer
        created_by:
          type: integer
        updated_by:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
  
