openapi: 3.0.0
info:
  title: MigrationDetailsResponse API
  version: 1.0.0
paths:
  /migration_details:
    get:
      operationId: listMigrationDetails
      summary: Get all migration_details
      responses:
        '200':
          description: List of migration_details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MigrationDetailsResponse'
    post:
      operationId: createMigrationDetail
      summary: Create a new migration_details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MigrationDetailsRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MigrationDetailsResponse'

  /migration_details/{id}:
    get:
      operationId: getMigrationDetailsById
      summary: Get migration_details by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: migration_details object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MigrationDetailsResponse'
    put:
      operationId: updateMigrationDetail
      summary: Update migration_details by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MigrationDetailsRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MigrationDetailsResponse'
    delete:
      operationId: deleteMigrationDetail
      summary: Delete migration_details by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    MigrationDetailsRequest:
      type: object
      properties:
        folder:
          type: string
          maxLength: 50
        year_folder:
          type: string
          maxLength: 50
        file_name:
          type: string
          maxLength: 255
        industry:
          type: string
          maxLength: 50
        execution_time:
          type: string
          format: date-time

    MigrationDetailsResponse:
      type: object
      properties:
        id:
          type: integer
        folder:
          type: string
          maxLength: 50
        year_folder:
          type: string
          maxLength: 50
        file_name:
          type: string
          maxLength: 255
        industry:
          type: string
          maxLength: 50
        execution_time:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  
