openapi: 3.0.0
info:
  title: RolesResponse API
  version: 1.0.0
paths:
  /roles:
    get:
      operationId: listRoles
      summary: Get all roles
      responses:
        '200':
          description: List of roles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RolesResponse'
    post:
      operationId: createRole
      summary: Create a new roles
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RolesRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RolesResponse'

  /roles/{id}:
    get:
      operationId: getRolesById
      summary: Get roles by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: roles object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RolesResponse'
    put:
      operationId: updateRole
      summary: Update roles by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RolesRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RolesResponse'
    delete:
      operationId: deleteRole
      summary: Delete roles by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    RolesRequest:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 50
        description:
          type: string
          maxLength: 300
        status:
          type: string
        is_admin:
          type: string

    RolesResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 50
        description:
          type: string
          maxLength: 300
        status:
          type: string
        is_admin:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  
