openapi: 3.0.0
info:
  title: FeatureFieldsResponse API
  version: 1.0.0
paths:
  /feature_fields:
    get:
      operationId: listFeatureFields
      summary: Get all feature_fields
      responses:
        '200':
          description: List of feature_fields
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FeatureFieldsResponse'
    post:
      operationId: createFeatureField
      summary: Create a new feature_fields
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FeatureFieldsRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeatureFieldsResponse'

  /feature_fields/{id}:
    get:
      operationId: getFeatureFieldsById
      summary: Get feature_fields by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: feature_fields object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeatureFieldsResponse'
    put:
      operationId: updateFeatureField
      summary: Update feature_fields by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FeatureFieldsRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeatureFieldsResponse'
    delete:
      operationId: deleteFeatureField
      summary: Delete feature_fields by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    FeatureFieldsRequest:
      type: object
      properties:
        id:
          type: integer
        module_block_id:
          type: integer
        field_name:
          type: string
          maxLength: 22
        field_key:
          type: string
          maxLength: 35
        is_required:
          type: string

    FeatureFieldsResponse:
      type: object
      properties:
        id:
          type: integer
        module_block_id:
          type: integer
        field_name:
          type: string
          maxLength: 22
        field_key:
          type: string
          maxLength: 35
        is_required:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  
