openapi: 3.0.0
info:
  title: SubscriptionPlansResponse API
  version: 1.0.0
paths:
  /subscription_plans:
    get:
      operationId: listSubscriptionPlans
      summary: Get all subscription_plans
      responses:
        '200':
          description: List of subscription_plans
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubscriptionPlansResponse'
    post:
      operationId: createSubscriptionPlan
      summary: Create a new subscription_plans
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionPlansRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionPlansResponse'

  /subscription_plans/{id}:
    get:
      operationId: getSubscriptionPlansById
      summary: Get subscription_plans by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: subscription_plans object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionPlansResponse'
    put:
      operationId: updateSubscriptionPlan
      summary: Update subscription_plans by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionPlansRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionPlansResponse'
    delete:
      operationId: deleteSubscriptionPlan
      summary: Delete subscription_plans by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    SubscriptionPlansRequest:
      type: object
      properties:
        id:
          type: integer
        plan_name:
          type: string
          maxLength: 30
        institute_type:
          type: string
          maxLength: 7
        monthly_price:
          type: number
        yearly_price:
          type: number
        max_users:
          type: integer
        max_students:
          type: integer
        features:
          type: object
        description:
          type: string
        status:
          type: string
        deleted_at:
          type: string
          format: date-time

    SubscriptionPlansResponse:
      type: object
      properties:
        id:
          type: integer
        plan_name:
          type: string
          maxLength: 30
        institute_type:
          type: string
          maxLength: 7
        monthly_price:
          type: number
        yearly_price:
          type: number
        max_users:
          type: integer
        max_students:
          type: integer
        features:
          type: object
        description:
          type: string
        status:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
  
