openapi: 3.0.3
info:
  title: Cpanel Route API
  version: 0.1.0
servers:
  - url: http://localhost:3001
paths:
  /cpanelroutes/:domain?:
    get:
      operationId: cpanelRouteDomain
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCpanelRouteDomainResponse'
components:
  schemas:
    GetCpanelRouteDomainResponse:
      type: object
      properties:
        domain:
          type: string
        domain_type:
          type: string
        domain_shortcode:
          type: string
        api_endpoint:
          type: string
        settings:
          type: object
          additionalProperties:
            type: string
        
      required: [domain]