openapi: 3.0.0
info:
  title: MasterPasswordsResponse API
  version: 1.0.0
paths:
  /master_passwords:
    get:
      operationId: listMasterPasswords
      summary: Get all master_passwords
      responses:
        '200':
          description: List of master_passwords
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MasterPasswordsResponse'
    post:
      operationId: createMasterPassword
      summary: Create a new master_passwords
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MasterPasswordsRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MasterPasswordsResponse'

  /master_passwords/{id}:
    get:
      operationId: getMasterPasswordsById
      summary: Get master_passwords by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: master_passwords object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MasterPasswordsResponse'
    put:
      operationId: updateMasterPassword
      summary: Update master_passwords by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MasterPasswordsRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MasterPasswordsResponse'
    delete:
      operationId: deleteMasterPassword
      summary: Delete master_passwords by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    MasterPasswordsRequest:
      type: object
      properties:
        default_username:
          type: string
          maxLength: 50
        application:
          type: string
          maxLength: 50
        created_by:
          type: integer
        updated_by:
          type: integer
        last_password_updated:
          type: string
          format: date-time
        from_cpanel:
          type: string
          maxLength: 50

    MasterPasswordsResponse:
      type: object
      properties:
        id:
          type: integer
        default_username:
          type: string
          maxLength: 50
        application:
          type: string
          maxLength: 50
        created_by:
          type: integer
        updated_by:
          type: integer
        last_password_updated:
          type: string
          format: date-time
        from_cpanel:
          type: string
          maxLength: 50
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  
