openapi: 3.0.0
info:
  title: IndustriesResponse API
  version: 1.0.0
paths:
  /industries:
    get:
      operationId: listIndustries
      summary: Get all industries
      responses:
        '200':
          description: List of industries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IndustriesResponse'
    post:
      operationId: createIndustrie
      summary: Create a new industries
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IndustriesRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndustriesResponse'

  /industries/{id}:
    get:
      operationId: getIndustriesById
      summary: Get industries by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: industries object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndustriesResponse'
    put:
      operationId: updateIndustrie
      summary: Update industries by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IndustriesRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndustriesResponse'
    delete:
      operationId: deleteIndustrie
      summary: Delete industries by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    IndustriesRequest:
      type: object
      properties:
        id:
          type: integer
        code:
          type: string
          maxLength: 8
        name:
          type: string
          maxLength: 7
        description:
          type: string
          maxLength: 17
        type:
          type: string
          maxLength: 8
        image:
          type: string
          maxLength: 12

    IndustriesResponse:
      type: object
      properties:
        id:
          type: integer
        code:
          type: string
          maxLength: 8
        name:
          type: string
          maxLength: 7
        description:
          type: string
          maxLength: 17
        type:
          type: string
          maxLength: 8
        image:
          type: string
          maxLength: 12
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  
