openapi: 3.0.0
info:
  title: InstituteDomainsResponse API
  version: 1.0.0
paths:
  /institute_domains:
    get:
      operationId: listInstituteDomains
      summary: Get all institute_domains
      responses:
        '200':
          description: List of institute_domains
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InstituteDomainsResponse'
    post:
      operationId: createInstituteDomain
      summary: Create a new institute_domains
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstituteDomainsRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstituteDomainsResponse'

  /institute_domains/{id}:
    get:
      operationId: getInstituteDomainsById
      summary: Get institute_domains by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: institute_domains object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstituteDomainsResponse'
    put:
      operationId: updateInstituteDomain
      summary: Update institute_domains by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstituteDomainsRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstituteDomainsResponse'
    delete:
      operationId: deleteInstituteDomain
      summary: Delete institute_domains by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    InstituteDomainsRequest:
      type: object
      properties:
        id:
          type: integer
        institute_id:
          type: integer
        domain:
          type: string
          maxLength: 100
        schema_name:
          type: string
          maxLength: 100
        is_primary:
          type: string
        status:
          type: string

    InstituteDomainsResponse:
      type: object
      properties:
        id:
          type: integer
        institute_id:
          type: integer
        domain:
          type: string
          maxLength: 100
        schema_name:
          type: string
          maxLength: 100
        is_primary:
          type: string
        status:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  
