openapi: 3.0.0
info:
  title: SubsResponse API
  version: 1.0.0
paths:
  /subs:
    get:
      operationId: listSubs
      summary: Get all subs
      responses:
        '200':
          description: List of subs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubsResponse'
    post:
      operationId: createSub
      summary: Create a new subs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubsRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubsResponse'

  /subs/{id}:
    get:
      operationId: getSubsById
      summary: Get subs by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: subs object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubsResponse'
    put:
      operationId: updateSub
      summary: Update subs by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubsRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubsResponse'
    delete:
      operationId: deleteSub
      summary: Delete subs by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    SubsRequest:
      type: object
      properties:
        customer_id:
          type: integer
        subdomain:
          type: string
          maxLength: 50
        protocol:
          type: string
          maxLength: 5
        shortname:
          type: string
          maxLength: 30
        database_name:
          type: string
          maxLength: 30
        name:
          type: string
          maxLength: 50
        logo:
          type: string
          maxLength: 255
        cloud_print_logo:
          type: string
          maxLength: 255
        logo_zpl:
          type: string
        site_logo:
          type: string
          maxLength: 255
        favicon_icon:
          type: string
          maxLength: 255
        mobile_logo:
          type: string
          maxLength: 255
        industry_id:
          type: integer
        package_id:
          type: integer
        environment_id:
          type: integer
        industry_environment_id:
          type: integer
        auth_key:
          type: string
          maxLength: 50
        decimal_value:
          type: integer
        s3_folder:
          type: string
          maxLength: 100
        status:
          type: string
        site_created:
          type: string
        allow_package_upgrade:
          type: string
        permission_based_on:
          type: string
        source_of_creation:
          type: string
        default_role:
          type: integer
        is_role_synced:
          type: string
        language_id:
          type: integer
        currency_id:
          type: integer
        bundle_retail_price:
          type: number
        billing_frequency:
          type: string
        signup_date:
          type: string
          format: date-time
        last_access:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time

    SubsResponse:
      type: object
      properties:
        id:
          type: integer
        customer_id:
          type: integer
        subdomain:
          type: string
          maxLength: 50
        protocol:
          type: string
          maxLength: 5
        shortname:
          type: string
          maxLength: 30
        database_name:
          type: string
          maxLength: 30
        name:
          type: string
          maxLength: 50
        logo:
          type: string
          maxLength: 255
        cloud_print_logo:
          type: string
          maxLength: 255
        logo_zpl:
          type: string
        site_logo:
          type: string
          maxLength: 255
        favicon_icon:
          type: string
          maxLength: 255
        mobile_logo:
          type: string
          maxLength: 255
        industry_id:
          type: integer
        package_id:
          type: integer
        environment_id:
          type: integer
        industry_environment_id:
          type: integer
        auth_key:
          type: string
          maxLength: 50
        decimal_value:
          type: integer
        s3_folder:
          type: string
          maxLength: 100
        status:
          type: string
        site_created:
          type: string
        allow_package_upgrade:
          type: string
        permission_based_on:
          type: string
        source_of_creation:
          type: string
        default_role:
          type: integer
        is_role_synced:
          type: string
        language_id:
          type: integer
        currency_id:
          type: integer
        bundle_retail_price:
          type: number
        billing_frequency:
          type: string
        signup_date:
          type: string
          format: date-time
        last_access:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
  
