openapi: 3.0.0
info:
  title: ServiceTicketCommentsResponse API
  version: 1.0.0
paths:
  /service_ticket_comments:
    get:
      operationId: listServiceTicketComments
      summary: Get all service_ticket_comments
      responses:
        '200':
          description: List of service_ticket_comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceTicketCommentsResponse'
    post:
      operationId: createServiceTicketComment
      summary: Create a new service_ticket_comments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceTicketCommentsRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceTicketCommentsResponse'

  /service_ticket_comments/{id}:
    get:
      operationId: getServiceTicketCommentsById
      summary: Get service_ticket_comments by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: service_ticket_comments object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceTicketCommentsResponse'
    put:
      operationId: updateServiceTicketComment
      summary: Update service_ticket_comments by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceTicketCommentsRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceTicketCommentsResponse'
    delete:
      operationId: deleteServiceTicketComment
      summary: Delete service_ticket_comments by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    ServiceTicketCommentsRequest:
      type: object
      properties:
        id:
          type: integer
        service_ticket_id:
          type: integer
        user_id:
          type: integer
        user_comment:
          type: string

    ServiceTicketCommentsResponse:
      type: object
      properties:
        id:
          type: integer
        service_ticket_id:
          type: integer
        user_id:
          type: integer
        user_comment:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  
