openapi: 3.0.0
info:
  title: CustomerStatusTimeLogsResponse API
  version: 1.0.0
paths:
  /customer_status_time_logs:
    get:
      operationId: listCustomerStatusTimeLogs
      summary: Get all customer_status_time_logs
      responses:
        '200':
          description: List of customer_status_time_logs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerStatusTimeLogsResponse'
    post:
      operationId: createCustomerStatusTimeLog
      summary: Create a new customer_status_time_logs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerStatusTimeLogsRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerStatusTimeLogsResponse'

  /customer_status_time_logs/{id}:
    get:
      operationId: getCustomerStatusTimeLogsById
      summary: Get customer_status_time_logs by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: customer_status_time_logs object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerStatusTimeLogsResponse'
    put:
      operationId: updateCustomerStatusTimeLog
      summary: Update customer_status_time_logs by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerStatusTimeLogsRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerStatusTimeLogsResponse'
    delete:
      operationId: deleteCustomerStatusTimeLog
      summary: Delete customer_status_time_logs by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    CustomerStatusTimeLogsRequest:
      type: object
      properties:
        id:
          type: integer
        customer_id:
          type: integer
        customer_status_id:
          type: integer
        hours_lapsed:
          type: integer
        minutes_lapsed:
          type: integer
        is_active:
          type: string
        created_by:
          type: integer
        start_time:
          type: string
          format: date-time
        cron_last_updated_at:
          type: string
          format: date-time

    CustomerStatusTimeLogsResponse:
      type: object
      properties:
        id:
          type: integer
        customer_id:
          type: integer
        customer_status_id:
          type: integer
        hours_lapsed:
          type: integer
        minutes_lapsed:
          type: integer
        is_active:
          type: string
        created_by:
          type: integer
        created_at:
          type: string
          format: date-time
        start_time:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        cron_last_updated_at:
          type: string
          format: date-time
  
