openapi: 3.0.0
info:
  title: CpanelsResponse API
  version: 1.0.0
paths:
  /cpanels:
    get:
      operationId: listCpanels
      summary: Get all cpanels
      responses:
        '200':
          description: List of cpanels
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CpanelsResponse'
    post:
      operationId: createCpanel
      summary: Create a new cpanels
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CpanelsRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CpanelsResponse'

  /cpanels/{id}:
    get:
      operationId: getCpanelsById
      summary: Get cpanels by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: cpanels object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CpanelsResponse'
    put:
      operationId: updateCpanel
      summary: Update cpanels by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CpanelsRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CpanelsResponse'
    delete:
      operationId: deleteCpanel
      summary: Delete cpanels by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    CpanelsRequest:
      type: object
      properties:
        domain:
          type: string
          maxLength: 100
        api_endpoint:
          type: string
          maxLength: 100
        settings:
          type: object

    CpanelsResponse:
      type: object
      properties:
        id:
          type: integer
        domain:
          type: string
          maxLength: 100
        api_endpoint:
          type: string
          maxLength: 100
        settings:
          type: object
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  
