openapi: 3.0.0
info:
  title: AdminUsersResponse API
  version: 1.0.0
paths:
  /admin_users:
    get:
      operationId: listAdminUsers
      summary: Get all admin_users
      responses:
        '200':
          description: List of admin_users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AdminUsersResponse'
    post:
      operationId: createAdminUser
      summary: Create a new admin_users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminUsersRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminUsersResponse'

  /admin_users/{id}:
    get:
      operationId: getAdminUsersById
      summary: Get admin_users by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: admin_users object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminUsersResponse'
    put:
      operationId: updateAdminUser
      summary: Update admin_users by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminUsersRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminUsersResponse'
    delete:
      operationId: deleteAdminUser
      summary: Delete admin_users by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    AdminUsersRequest:
      type: object
      properties:
        username:
          type: string
          maxLength: 22
        email:
          type: string
          maxLength: 26
        password:
          type: string
          maxLength: 250
        first_name:
          type: string
          maxLength: 50
        last_name:
          type: string
          maxLength: 50
        phone:
          type: string
          maxLength: 15
        role:
          type: string
          maxLength: 13
        profile_image:
          type: string
          maxLength: 255
        is_verified:
          type: integer
        last_login:
          type: string
          format: date-time
        status:
          type: string
        password_reset_token:
          type: string
          maxLength: 255
        password_reset_expires:
          type: string
          format: date-time

    AdminUsersResponse:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
          maxLength: 22
        email:
          type: string
          maxLength: 26
        password:
          type: string
          maxLength: 250
        first_name:
          type: string
          maxLength: 50
        last_name:
          type: string
          maxLength: 50
        phone:
          type: string
          maxLength: 15
        role:
          type: string
          maxLength: 13
        profile_image:
          type: string
          maxLength: 255
        is_verified:
          type: integer
        last_login:
          type: string
          format: date-time
        status:
          type: string
        password_reset_token:
          type: string
          maxLength: 255
        password_reset_expires:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  
