openapi: 3.0.0
info:
  title: CustomerExportTemplatesResponse API
  version: 1.0.0
paths:
  /customer_export_templates:
    get:
      operationId: listCustomerExportTemplates
      summary: Get all customer_export_templates
      responses:
        '200':
          description: List of customer_export_templates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerExportTemplatesResponse'
    post:
      operationId: createCustomerExportTemplate
      summary: Create a new customer_export_templates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerExportTemplatesRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerExportTemplatesResponse'

  /customer_export_templates/{id}:
    get:
      operationId: getCustomerExportTemplatesById
      summary: Get customer_export_templates by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: customer_export_templates object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerExportTemplatesResponse'
    put:
      operationId: updateCustomerExportTemplate
      summary: Update customer_export_templates by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerExportTemplatesRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerExportTemplatesResponse'
    delete:
      operationId: deleteCustomerExportTemplate
      summary: Delete customer_export_templates by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    CustomerExportTemplatesRequest:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 200
        is_default:
          type: string

    CustomerExportTemplatesResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 200
        is_default:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  
