openapi: 3.0.0
info:
  title: ServiceTicketUserContentsResponse API
  version: 1.0.0
paths:
  /service_ticket_user_contents:
    get:
      operationId: listServiceTicketUserContents
      summary: Get all service_ticket_user_contents
      responses:
        '200':
          description: List of service_ticket_user_contents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceTicketUserContentsResponse'
    post:
      operationId: createServiceTicketUserContent
      summary: Create a new service_ticket_user_contents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceTicketUserContentsRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceTicketUserContentsResponse'

  /service_ticket_user_contents/{id}:
    get:
      operationId: getServiceTicketUserContentsById
      summary: Get service_ticket_user_contents by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: service_ticket_user_contents object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceTicketUserContentsResponse'
    put:
      operationId: updateServiceTicketUserContent
      summary: Update service_ticket_user_contents by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceTicketUserContentsRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceTicketUserContentsResponse'
    delete:
      operationId: deleteServiceTicketUserContent
      summary: Delete service_ticket_user_contents by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    ServiceTicketUserContentsRequest:
      type: object
      properties:
        id:
          type: integer
        service_ticket_id:
          type: integer
        customer_id:
          type: integer
        sub_id:
          type: integer
        user_id:
          type: integer
        content:
          type: string
        deleted_at:
          type: string
          format: date-time

    ServiceTicketUserContentsResponse:
      type: object
      properties:
        id:
          type: integer
        service_ticket_id:
          type: integer
        customer_id:
          type: integer
        sub_id:
          type: integer
        user_id:
          type: integer
        content:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
  
