openapi: 3.0.0
info:
  title: SubModulesResponse API
  version: 1.0.0
paths:
  /sub_modules:
    get:
      operationId: listSubModules
      summary: Get all sub_modules
      responses:
        '200':
          description: List of sub_modules
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubModulesResponse'
    post:
      operationId: createSubModule
      summary: Create a new sub_modules
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubModulesRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubModulesResponse'

  /sub_modules/{id}:
    get:
      operationId: getSubModulesById
      summary: Get sub_modules by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: sub_modules object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubModulesResponse'
    put:
      operationId: updateSubModule
      summary: Update sub_modules by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubModulesRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubModulesResponse'
    delete:
      operationId: deleteSubModule
      summary: Delete sub_modules by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    SubModulesRequest:
      type: object
      properties:
        id:
          type: integer
        sub_id:
          type: integer
        module_id:
          type: integer
        deleted_at:
          type: string
          format: date-time

    SubModulesResponse:
      type: object
      properties:
        id:
          type: integer
        sub_id:
          type: integer
        module_id:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
  
