openapi: 3.0.0
info:
  title: CustomerDiscountsResponse API
  version: 1.0.0
paths:
  /customer_discounts:
    get:
      operationId: listCustomerDiscounts
      summary: Get all customer_discounts
      responses:
        '200':
          description: List of customer_discounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerDiscountsResponse'
    post:
      operationId: createCustomerDiscount
      summary: Create a new customer_discounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDiscountsRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDiscountsResponse'

  /customer_discounts/{id}:
    get:
      operationId: getCustomerDiscountsById
      summary: Get customer_discounts by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: customer_discounts object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDiscountsResponse'
    put:
      operationId: updateCustomerDiscount
      summary: Update customer_discounts by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDiscountsRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDiscountsResponse'
    delete:
      operationId: deleteCustomerDiscount
      summary: Delete customer_discounts by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    CustomerDiscountsRequest:
      type: object
      properties:
        id:
          type: integer
        customer_id:
          type: integer
        package_id:
          type: integer
        sub_id:
          type: integer
        discount_percentage:
          type: number
        discount_duration:
          type: integer
        discount_used:
          type: integer

    CustomerDiscountsResponse:
      type: object
      properties:
        id:
          type: integer
        customer_id:
          type: integer
        package_id:
          type: integer
        sub_id:
          type: integer
        discount_percentage:
          type: number
        discount_duration:
          type: integer
        discount_used:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  
