openapi: 3.0.0
info:
  title: CustomerNumbersResponse API
  version: 1.0.0
paths:
  /customer_numbers:
    get:
      operationId: listCustomerNumbers
      summary: Get all customer_numbers
      responses:
        '200':
          description: List of customer_numbers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerNumbersResponse'
    post:
      operationId: createCustomerNumber
      summary: Create a new customer_numbers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerNumbersRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerNumbersResponse'

  /customer_numbers/{id}:
    get:
      operationId: getCustomerNumbersById
      summary: Get customer_numbers by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: customer_numbers object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerNumbersResponse'
    put:
      operationId: updateCustomerNumber
      summary: Update customer_numbers by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerNumbersRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerNumbersResponse'
    delete:
      operationId: deleteCustomerNumber
      summary: Delete customer_numbers by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    CustomerNumbersRequest:
      type: object
      properties:
        id:
          type: integer
        module:
          type: string
          maxLength: 14
        prefix:
          type: string
          maxLength: 4
        next_no:
          type: integer

    CustomerNumbersResponse:
      type: object
      properties:
        id:
          type: integer
        module:
          type: string
          maxLength: 14
        prefix:
          type: string
          maxLength: 4
        next_no:
          type: integer
  
