openapi: 3.0.0
info:
  title: SubPackagesResponse API
  version: 1.0.0
paths:
  /sub_packages:
    get:
      operationId: listSubPackages
      summary: Get all sub_packages
      responses:
        '200':
          description: List of sub_packages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubPackagesResponse'
    post:
      operationId: createSubPackage
      summary: Create a new sub_packages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubPackagesRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubPackagesResponse'

  /sub_packages/{id}:
    get:
      operationId: getSubPackagesById
      summary: Get sub_packages by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: sub_packages object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubPackagesResponse'
    put:
      operationId: updateSubPackage
      summary: Update sub_packages by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubPackagesRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubPackagesResponse'
    delete:
      operationId: deleteSubPackage
      summary: Delete sub_packages by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    SubPackagesRequest:
      type: object
      properties:
        id:
          type: integer
        sub_id:
          type: integer
        package_id:
          type: integer
        package_name:
          type: string
          maxLength: 200
        package_price:
          type: integer
        package_max_user:
          type: integer
        package_max_product:
          type: integer
        permission_based_on:
          type: string
        additional_users:
          type: integer
        additional_store_price:
          type: number
        additional_user_price:
          type: number
        discount:
          type: number
        billing_date:
          type: string
          format: date-time
        expiry_date:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time

    SubPackagesResponse:
      type: object
      properties:
        id:
          type: integer
        sub_id:
          type: integer
        package_id:
          type: integer
        package_name:
          type: string
          maxLength: 200
        package_price:
          type: integer
        package_max_user:
          type: integer
        package_max_product:
          type: integer
        permission_based_on:
          type: string
        additional_users:
          type: integer
        additional_store_price:
          type: number
        additional_user_price:
          type: number
        discount:
          type: number
        billing_date:
          type: string
          format: date-time
        expiry_date:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
  
