openapi: 3.0.0
info:
  title: CustomerNotesResponse API
  version: 1.0.0
paths:
  /customer_notes:
    get:
      operationId: listCustomerNotes
      summary: Get all customer_notes
      responses:
        '200':
          description: List of customer_notes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerNotesResponse'
    post:
      operationId: createCustomerNote
      summary: Create a new customer_notes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerNotesRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerNotesResponse'

  /customer_notes/{id}:
    get:
      operationId: getCustomerNotesById
      summary: Get customer_notes by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: customer_notes object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerNotesResponse'
    put:
      operationId: updateCustomerNote
      summary: Update customer_notes by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerNotesRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerNotesResponse'
    delete:
      operationId: deleteCustomerNote
      summary: Delete customer_notes by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    CustomerNotesRequest:
      type: object
      properties:
        id:
          type: integer
        customer_id:
          type: integer
        subject:
          type: string
          maxLength: 50
        description:
          type: string
          maxLength: 500
        assignee_id:
          type: integer
        created_by:
          type: integer
        updated_by:
          type: integer
        deleted_at:
          type: string
          format: date-time

    CustomerNotesResponse:
      type: object
      properties:
        id:
          type: integer
        customer_id:
          type: integer
        subject:
          type: string
          maxLength: 50
        description:
          type: string
          maxLength: 500
        assignee_id:
          type: integer
        created_by:
          type: integer
        updated_by:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
  
