openapi: 3.0.0
info:
  title: ServiceTicketTypeLogsResponse API
  version: 1.0.0
paths:
  /service_ticket_type_logs:
    get:
      operationId: listServiceTicketTypeLogs
      summary: Get all service_ticket_type_logs
      responses:
        '200':
          description: List of service_ticket_type_logs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceTicketTypeLogsResponse'
    post:
      operationId: createServiceTicketTypeLog
      summary: Create a new service_ticket_type_logs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceTicketTypeLogsRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceTicketTypeLogsResponse'

  /service_ticket_type_logs/{id}:
    get:
      operationId: getServiceTicketTypeLogsById
      summary: Get service_ticket_type_logs by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: service_ticket_type_logs object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceTicketTypeLogsResponse'
    put:
      operationId: updateServiceTicketTypeLog
      summary: Update service_ticket_type_logs by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceTicketTypeLogsRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceTicketTypeLogsResponse'
    delete:
      operationId: deleteServiceTicketTypeLog
      summary: Delete service_ticket_type_logs by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    ServiceTicketTypeLogsRequest:
      type: object
      properties:
        id:
          type: integer
        service_ticket_id:
          type: integer
        service_ticket_type_id:
          type: integer
        hours_lapsed:
          type: string
          maxLength: 1
        minutes_lapsed:
          type: string
          maxLength: 1
        is_active:
          type: string
        created_by:
          type: integer
        ticket_start_time:
          type: string
          format: date-time
        cron_last_updated_at:
          type: string
          format: date-time

    ServiceTicketTypeLogsResponse:
      type: object
      properties:
        id:
          type: integer
        service_ticket_id:
          type: integer
        service_ticket_type_id:
          type: integer
        hours_lapsed:
          type: string
          maxLength: 1
        minutes_lapsed:
          type: string
          maxLength: 1
        is_active:
          type: string
        created_by:
          type: integer
        ticket_start_time:
          type: string
          format: date-time
        cron_last_updated_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  
