openapi: 3.0.0
info:
  title: EnvironmentsResponse API
  version: 1.0.0
paths:
  /environments:
    get:
      operationId: listEnvironments
      summary: Get all environments
      responses:
        '200':
          description: List of environments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EnvironmentsResponse'
    post:
      operationId: createEnvironment
      summary: Create a new environments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnvironmentsRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnvironmentsResponse'

  /environments/{id}:
    get:
      operationId: getEnvironmentsById
      summary: Get environments by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: environments object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnvironmentsResponse'
    put:
      operationId: updateEnvironment
      summary: Update environments by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnvironmentsRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnvironmentsResponse'
    delete:
      operationId: deleteEnvironment
      summary: Delete environments by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    EnvironmentsRequest:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 30
        code:
          type: string
          maxLength: 30

    EnvironmentsResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          maxLength: 30
        code:
          type: string
          maxLength: 30
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  
