openapi: 3.0.0
info:
  title: CustomerStatusLogsResponse API
  version: 1.0.0
paths:
  /customer_status_logs:
    get:
      operationId: listCustomerStatusLogs
      summary: Get all customer_status_logs
      responses:
        '200':
          description: List of customer_status_logs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerStatusLogsResponse'
    post:
      operationId: createCustomerStatusLog
      summary: Create a new customer_status_logs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerStatusLogsRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerStatusLogsResponse'

  /customer_status_logs/{id}:
    get:
      operationId: getCustomerStatusLogsById
      summary: Get customer_status_logs by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: customer_status_logs object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerStatusLogsResponse'
    put:
      operationId: updateCustomerStatusLog
      summary: Update customer_status_logs by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerStatusLogsRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerStatusLogsResponse'
    delete:
      operationId: deleteCustomerStatusLog
      summary: Delete customer_status_logs by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    CustomerStatusLogsRequest:
      type: object
      properties:
        id:
          type: integer
        customer_id:
          type: integer
        status_id:
          type: integer
        deleted_at:
          type: string
          format: date-time

    CustomerStatusLogsResponse:
      type: object
      properties:
        id:
          type: integer
        customer_id:
          type: integer
        status_id:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
  
