openapi: 3.0.0
info:
  title: MasterCredentialsResponse API
  version: 1.0.0
paths:
  /master_credentials:
    get:
      operationId: listMasterCredentials
      summary: Get all master_credentials
      responses:
        '200':
          description: List of master_credentials
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MasterCredentialsResponse'
    post:
      operationId: createMasterCredential
      summary: Create a new master_credentials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MasterCredentialsRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MasterCredentialsResponse'

  /master_credentials/{id}:
    get:
      operationId: getMasterCredentialsById
      summary: Get master_credentials by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: master_credentials object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MasterCredentialsResponse'
    put:
      operationId: updateMasterCredential
      summary: Update master_credentials by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MasterCredentialsRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MasterCredentialsResponse'
    delete:
      operationId: deleteMasterCredential
      summary: Delete master_credentials by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    MasterCredentialsRequest:
      type: object
      properties:
        id:
          type: integer
        institute_id:
          type: integer
        username:
          type: string
          maxLength: 30
        application:
          type: string
          maxLength: 10
        password:
          type: string
          maxLength: 250
        created_by:
          type: integer
        updated_by:
          type: integer
        last_password_updated:
          type: string
          format: date-time
        from_domain:
          type: string
          maxLength: 100

    MasterCredentialsResponse:
      type: object
      properties:
        id:
          type: integer
        institute_id:
          type: integer
        username:
          type: string
          maxLength: 30
        application:
          type: string
          maxLength: 10
        password:
          type: string
          maxLength: 250
        created_by:
          type: integer
        updated_by:
          type: integer
        last_password_updated:
          type: string
          format: date-time
        from_domain:
          type: string
          maxLength: 100
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  
