openapi: 3.0.0
info:
  title: IndustryEnvironmentsResponse API
  version: 1.0.0
paths:
  /industry_environments:
    get:
      operationId: listIndustryEnvironments
      summary: Get all industry_environments
      responses:
        '200':
          description: List of industry_environments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IndustryEnvironmentsResponse'
    post:
      operationId: createIndustryEnvironment
      summary: Create a new industry_environments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IndustryEnvironmentsRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndustryEnvironmentsResponse'

  /industry_environments/{id}:
    get:
      operationId: getIndustryEnvironmentsById
      summary: Get industry_environments by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: industry_environments object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndustryEnvironmentsResponse'
    put:
      operationId: updateIndustryEnvironment
      summary: Update industry_environments by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IndustryEnvironmentsRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndustryEnvironmentsResponse'
    delete:
      operationId: deleteIndustryEnvironment
      summary: Delete industry_environments by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    IndustryEnvironmentsRequest:
      type: object
      properties:
        id:
          type: integer
        industry_id:
          type: integer
        environment_id:
          type: integer
        configuration:
          type: object

    IndustryEnvironmentsResponse:
      type: object
      properties:
        id:
          type: integer
        industry_id:
          type: integer
        environment_id:
          type: integer
        configuration:
          type: object
  
