openapi: 3.0.0
info:
  title: ServiceTicketLogsResponse API
  version: 1.0.0
paths:
  /service_ticket_logs:
    get:
      operationId: listServiceTicketLogs
      summary: Get all service_ticket_logs
      responses:
        '200':
          description: List of service_ticket_logs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceTicketLogsResponse'
    post:
      operationId: createServiceTicketLog
      summary: Create a new service_ticket_logs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceTicketLogsRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceTicketLogsResponse'

  /service_ticket_logs/{id}:
    get:
      operationId: getServiceTicketLogsById
      summary: Get service_ticket_logs by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: service_ticket_logs object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceTicketLogsResponse'
    put:
      operationId: updateServiceTicketLog
      summary: Update service_ticket_logs by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceTicketLogsRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceTicketLogsResponse'
    delete:
      operationId: deleteServiceTicketLog
      summary: Delete service_ticket_logs by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
components:
  schemas:

    ServiceTicketLogsRequest:
      type: object
      properties:
        id:
          type: integer
        ticket_id:
          type: integer
        ticket_type_id:
          type: integer
        created_by:
          type: integer

    ServiceTicketLogsResponse:
      type: object
      properties:
        id:
          type: integer
        ticket_id:
          type: integer
        ticket_type_id:
          type: integer
        created_by:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  
